// <auto-generated />
using Lab18Tom.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab18Tom.Migrations
{
    [DbContext(typeof(Lab18TomContext))]
    [Migration("20171005203807_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab18Tom.Models.Destinations", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.HasKey("DestinationID");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Lab18Tom.Models.DestinationSupplies", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DestinationsDestinationID");

                    b.Property<int>("SuppyID");

                    b.HasKey("DestinationID");

                    b.HasIndex("DestinationsDestinationID");

                    b.ToTable("DestinationSupplies");
                });

            modelBuilder.Entity("Lab18Tom.Models.Supplies", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinationID");

                    b.Property<bool>("IsRequired");

                    b.Property<string>("Name");

                    b.Property<int>("Qty");

                    b.Property<decimal>("Volume");

                    b.Property<decimal>("Weight");

                    b.HasKey("SupplyID");

                    b.HasIndex("DestinationID")
                        .IsUnique();

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Lab18Tom.Models.DestinationSupplies", b =>
                {
                    b.HasOne("Lab18Tom.Models.Destinations", "Destinations")
                        .WithMany()
                        .HasForeignKey("DestinationsDestinationID");
                });

            modelBuilder.Entity("Lab18Tom.Models.Supplies", b =>
                {
                    b.HasOne("Lab18Tom.Models.DestinationSupplies")
                        .WithOne("Supplies")
                        .HasForeignKey("Lab18Tom.Models.Supplies", "DestinationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
